default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: saas_development
  username: postgres
  password: 
  host: localhost

test:
  <<: *default
  database: saas_test
  username: postgres
  password: 
  host: localhost

production:
  <<: *default
  database: saas_production
  username: saas
  password: <%= ENV['SAAS_DATABASE_PASSWORD'] %>
